// <auto-generated />
using MicroServiceCrudUser.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroServiceCrudUser.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MicroServiceCrudUser.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            PasswordHash = "hash1",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            PasswordHash = "hash2",
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.brown@example.com",
                            PasswordHash = "hash3",
                            Username = "michaelbrown"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lisa.jones@example.com",
                            PasswordHash = "hash4",
                            Username = "lisajones"
                        },
                        new
                        {
                            Id = 5,
                            Email = "chris.miller@example.com",
                            PasswordHash = "hash5",
                            Username = "chrismiller"
                        },
                        new
                        {
                            Id = 6,
                            Email = "patricia.wilson@example.com",
                            PasswordHash = "hash6",
                            Username = "patriciawilson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "robert.taylor@example.com",
                            PasswordHash = "hash7",
                            Username = "roberttaylor"
                        },
                        new
                        {
                            Id = 8,
                            Email = "linda.moore@example.com",
                            PasswordHash = "hash8",
                            Username = "lindamoore"
                        },
                        new
                        {
                            Id = 9,
                            Email = "william.thomas@example.com",
                            PasswordHash = "hash9",
                            Username = "williamthomas"
                        },
                        new
                        {
                            Id = 10,
                            Email = "barbara.clark@example.com",
                            PasswordHash = "hash10",
                            Username = "barbaraclark"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
