version: '3.4'

services:
  microservicecruduser:
    image: ${DOCKER_REGISTRY-}microservicecruduser
    build:
      context: .
      dockerfile: MicroServiceCrudUser/Dockerfile
      
    ports:
        - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=server=localhost;Port=3307;DataBase=user_db;Uid=root;Pwd='5028';

  mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: '5028'
       MYSQL_DATABASE: user_db
    ports:
        - "3307:3306"
    volumes:
        - mysql-data:/var/lib/mysql

volumes:
  mysql-data: